"""Init migration 2

Revision ID: d78bdd6fd10f
Revises: 2e952bdb7f75
Create Date: 2023-12-08 23:34:46.080670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78bdd6fd10f'
down_revision: Union[str, None] = '2e952bdb7f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('city', sa.Column('post_index', sa.INTEGER(), nullable=True))
    op.add_column('city', sa.Column('utc_offset', sa.INTEGER(), nullable=False))
    op.add_column('city', sa.Column('lat', sa.FLOAT(), nullable=False))
    op.add_column('city', sa.Column('lon', sa.FLOAT(), nullable=False))
    op.add_column('city', sa.Column('population', sa.INTEGER(), nullable=True))
    op.add_column('city', sa.Column('region_id', sa.Integer(), nullable=False))
    op.drop_index('ix_city_name', table_name='city')
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    op.create_foreign_key(None, 'city', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.create_index('ix_city_name', 'city', ['name'], unique=False)
    op.drop_column('city', 'region_id')
    op.drop_column('city', 'population')
    op.drop_column('city', 'lon')
    op.drop_column('city', 'lat')
    op.drop_column('city', 'utc_offset')
    op.drop_column('city', 'post_index')
    op.drop_table('region')
    # ### end Alembic commands ###
